### ISSUE TITLE
Extend the concept?

### ISSUE THREAD

**Issue by moonheart08** [jonay2000/label#25]
It'd be neat/useful if Label could be used for same-type statics or consts, alongside functions. Not real sure how this'd work, you probably know better than I do.

**Comment by jonay2000** [comment]
Iteresting idea. I have been thinking about this as well. What would you propose the interface would be for that?  I don't think you can iterate over structs because structs are types, and every struct has a different type.

**Comment by jonay2000** [comment]
I think if I would support that, the final result would be very close to [David Tolnay's](https://github.com/dtolnay) [Inventory](https://github.com/dtolnay/inventory)

**Comment by jonay2000** [comment]
What do you think about a syntax close to this?

```rust
use label::create_label;


create_label!(
    static varname: usize;
);

#[varname::label]
static A: usize = 3;

#[varname::label]
static B: usize = 3;

fn main() {
    for i in varname::iter() {
        println!("{}", i);
    }
}


```

**Comment by jonay2000** [comment]
@moonheart08 #26
